# Generated by Django 4.1.7 on 2023-04-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_category_title_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_refused',
            field=models.BooleanField(default=False, verbose_name='Отказана'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_single',
            field=models.CharField(max_length=50, verbose_name='Название в ед. числе'),
        ),
    ]
