# Generated by Django 4.1.7 on 2023-04-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles_is_refused_alter_articles_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='is_refused',
        ),
        migrations.AddField(
            model_name='articles',
            name='acceptance_stage',
            field=models.IntegerField(default=0, verbose_name='Стадии принятия'),
        ),
    ]
